### PR TITLE
add _length2d virtual column for pipes

### PR DESCRIPTION
**Pull request by tudorbarascu**
Follow-up http://github.com/qwat/qwat-data-model/commit/db00335b7befbdd069a1978b71258ee2035d41d6

See http://github.com/qwat/qwat-data-model/issues/96

### CODE REVIEW

**Comment by 3nids** [comment]
hmmm, sorry I did not understood you wanted to switch for a permanent virtual columns.
What is the interest then?
I think postgresql will be much more powerful to perform the calculation.
Moreover, I realize now that I am using the length in labeling rules....

I am not sure anymore. Thoughts?

**Comment by tudorbarascu** [comment]
Indeed, postgresql is more performant than QGIS at calculation.
As written in https://github.com/qwat/qwat-data-model/issues/96 the advantages would be:
- a pipe that's not saved in the db-side will have the length already calculated on the QGIS side
- dropping a column that's somewhat redundant as we can calculate it
- shrinks the pipe data transferred over the network (just a little bit but still..)
- I tested with 17 000 pipes and I couldn't see any difference between using virtual column or from the db side, so the performance penalty is clearly negligible
- the labeling rules shouldn't suffer as they're simply based on the virtual column now, right?

**Comment by 3nids** [comment]
To me disadvantages:

* QGIS calculation overhead is worse than a few bytes of data transfer (neglectible if you consider you have 3 geometry columns, so probably something like 0.01% of the data)
* if used on rules, you can't have server side compilation (QGIS can transfer rules to the server to be more performant, but it won't be able to do it if we introduce functions like this)
* we drop a column to add another one in QGIS

Now, the only truly valid advantage to me is the unsaved features. But it doesn't sound that bad to me.

**Comment by tudorbarascu** [comment]
Yes, it's really negligible when considering the 2 extra geometry columns. On that, I haven't checked if the extra columns are currently filled automatically all the time as I am not using them (I know they did so in the past but there are some commits that may have fixed this). In case the db logic is still the same it would be good to rework it so that those columns get filled only when needed.

I haven't thought on the second point disadvantage that you raised and it's valid enough. I cannot currently imagine to what rules on length would serve but they may be cases.

On the third point, yes, to me it sounds better to drop server columns in favor of client side.

To conclude, I'm still inclined to do it, just a little though so you can revert if you please :).
All the best Denis, thanks for your work :smile:

**Comment by 3nids** [comment]
hi Tudor,

After discussion with Oslandia, we decided to revert https://github.com/qwat/qwat-data-model/commit/db00335b7befbdd069a1978b71258ee2035d41d6 and keep this in the view. 
To us, the advantage of calculation on the server is worth the fact that you don't have true value for editted-but-not-yet-commited features.
I hope you are fine with this change.

**Comment by tudorbarascu** [comment]
Hi Denis,
That was the clear path :).
It's fine by me, I wanted to ask you this days who will revert it.
All the best and thanks.

**Pull request closed without merging**
