### PR TITLE
qwat dictionary that translates ui's into english+romanian

### PR DESCRIPTION
**Pull request by tudorbarascu**

### CODE REVIEW

**Comment by 3nids** [comment]
can you write a short description of what is doing (and how it is doing it) the proposed code?
best wishes,
denis

**Comment by tudorbarascu** [comment]
Yes, I will complete it also with the developer stuff so that others can easily translate. Working on it right now.

**Comment by 3nids** [comment]
perfect, thanks!

**Comment by tudorbarascu** [comment]
Hi, you think ,should I add something more or have you got any suggestions/comments?

**Comment by 3nids** [comment]
sorry, I did not see the commit before.
that sounds good.
merging and will test later on.

**Pull request merged**
