### PR TITLE
Miscelaneous, little improvements

### PR DESCRIPTION
**Pull request by tpo**
Hello Denis,

so I was trying to get this module to run and the changes in this pull request mark my progress:

- I've added some infos in the README on how to install qwat
- I've added the 'qgiscombomanager' submodule, that is required to run qwat
- I've removed the dependency on 'MySettingsDialog', since no such module exists, and it doesn't actually seem to be used by qwat

So, if you don't mind, please pull.

But this is where I'm stuck, the plugin is loaded and I can load the qwat_offline project which bombards me with errors or I can load the qwat project which won't stop asking me to enter my credentials for a "qwat" service, which fails no matter what.

### CODE REVIEW

**Comment by 3nids** [comment]
Hi,
Thank you for your input.
I am very sorry you spent time on this plugin but it is deprecated, I will remove it.
FYI, the qgiscombomanager submodule has been merged into qgis core (QgsVectorLayerCombo, QgsFieldCombo).
For now, there is no need for a specific plugin to work with qwat.
You just need the data model and the project.

Sorry again for that.

**Comment by tpo** [comment]
Hello Denis,

thanks a lot for your answer.

Could you explain what will happen to the qwat? Will you just delete it from github or will there be a replacement project somewhere in parallel? Or does it allready exist somewhere (where?)?

Wrt the qgiscombomanager module - the problem is that at least as of QGIS 2.8, when loading the module QGIS will complain that there is no such module as qgiscombomanager. So maybe it needs the correct import statement in the code?

**Comment by 3nids** [comment]
Well, there are 2 repos that will remain: this one (qwat) and qwat-data-model.

I separated some time ago the model from this one, as I believe they are two distinct things.

The qwat repo contains everything that is needed to display the data in QGIS (project, forms, symbols, etc.) and maybe some tools (for migration, inspection, whatever).

The plugin was used at some point to interact with the db. It was never achieved, is not required anymore. The qgiscombomanager was required at the time I wrote the plugin, it would not be the case anymore. But as written, the plugin is outdated. So, I will only delete the qgis-plugin from this repo.

I hope it's a bit clearer!

**Comment by tudorbarascu** [comment]
I would like to add to what Denis said that you can use the qwat dictionary plugin if you want to use the forms in another language then french/romanian.

**Pull request closed without merging**
