### PR TITLE
added the not null constraints for pipes

### PR DESCRIPTION
**Pull request by tudorbarascu**
As the not null constraint in forms is working ok, I think we should add the constraints in the baseline project.

### CODE REVIEW

**Comment by tudorbarascu** [comment]
I would like to mirror all the constraints that are on the db side in the forms.

Any opinions on this?

**Comment by haubourg** [comment]
That is a long standing issue and I thought we needed to rework to forms to use Drag and drop form to take benefit of constraints. 
Lausanne already did a great form rework but based on old 0.1 model. If you're available to work on this, count on me to help and test

**Comment by haubourg** [comment]
And I was wrong about constraints and drag & drop , it works even with custom UI. So a big +1 here. 
Will you add other constraints in that PR?

**Comment by tudorbarascu** [comment]
I haven't tried with all the forms.. but at least for pipes, it works right of the box.
So there's no need to wait for forms reworking to have this.
It looks like:
peek 2017-07-04 19-27

One nice thing I just noticed is that although there are multiple not null constraints, you see maximum 3 at a time so that the form doesn't get crowded.

There is one small usability caveat, if you have not null constraints in other tabs, you are not suggested in which tab to look for.

It would have been nice if parent tabs would have the title in RED also (tabTextColor).

@haubourg Yes, I would like to all the other constraints but I was waiting for confirmation from others so that I can proceed.

I can also work on the forms.
Should I proceed from what Lausanne has done?
Are those UI's published somewhere?

**Comment by haubourg** [comment]
@tudor, currently I only saw them on the demo vidéos here https://share.oslandia.net/ws-qWAT/communication/video_demo/LAUSANNE_POC (Tell me if you don't have access to it)

@dsavary Could you share the qlr definitions (But I'm not sure how we can transfert it to a more recent QWAT project )

**Comment by tudorbarascu** [comment]
@haubourg I think only the ui's are necessary.

**Comment by haubourg** [comment]
> @haubourg I think only the ui's are necessary.
These are drag and drop forms now, so no more UI file, it's all in layer definition... UI are definitly easier to exchange..

**Comment by tudorbarascu** [comment]
@qwat/qwat-psc I have some time on my hands the following days and I would like to work on this.
It would be great if you could give your opinion, share work that's already been done etc. so I can start.

**Comment by haubourg** [comment]
Just tested and it's good to me. Let's merge! (if anyone objects, revert is still possible )

**Pull request merged**
