### PR TITLE
add document management system setup in project

### PR DESCRIPTION
**Pull request by 3nids**
for review, the polymorphic relations are implemented.
The form is configured on the document side, and for features on "ouvrages" layer only for now.

This goes along with datamodel update https://github.com/qwat/qwat-data-model/pull/344

### CODE REVIEW

**Comment by ponceta** [comment]
Hi @3nids,

I tested the project and it seems to work but with some bugs :

- [ ] Apple fonts.
- [ ] White screen on opening every form -> performance issue which is critical.
- [ ] identifier and type not filled and identifier blocking the OK button (if these are not auto field I'm not certain of their usability).

Quick demo on video :
https://git.oslandia.net/Oslandia-utilities/demandes_qwat_qgep/uploads/f6d4cb82ab46dfb072781e4cb9df1550/Tests_Document_Management_System_TEKSI_water_module_QWAT.mp4

**Comment by 3nids** [comment]
Last commit fixes:
* QGIS version (3.22)
* no OS specific fonts

Performance in plugin has been fixed in version 0.3.1 https://github.com/opengisch/qgis-document-management-system-plugin/releases/tag/0.3.1

identifier can now be NULL, type is now a foreign key to a value list table
see https://github.com/qwat/qwat-data-model/pull/362

**Review by ponceta — COMMENTED** [review]
Check

**Comment by ponceta** [comment]
@3nids you removed the "sql=" statement at the end of each 3.22 layer, is this a good practice in general (meaning it could be removed in qgep too?)

**Pull request merged**
