### PR TITLE
Updated subcriber and installation forms with recent data model updates

### PR DESCRIPTION
**Pull request by tudorbarascu**
They look like this.

proposal

### CODE REVIEW

**Comment by tudorbarascu** [comment]
Basically, I added altitude/altitude precision and remark to installation form and current flow + planned to subscriber. Is `débit prévu` text ok as planned flow label?

**Comment by 3nids** [comment]
Hi Tudor,
Thanks for the input.
Sorry for the silence, having hardware troubles + plans to prepare.

**Comment by tudorbarascu** [comment]
Hi Denis, no worries.
Now that you've accepted the pull, I will make another one with the updated translations.
Regarding the fk_folder column, I noticed you only worked on the pipe form and field widget although the commit was also for valve and hydrant.
Are you planning to work on the valve and hydrant forms/widget also?

**Comment by 3nids** [comment]
feel free to update them too, or I'll do it later on

**Pull request merged**
