### PR TITLE
Update README with submodule + db

### PR DESCRIPTION
**Pull request by schoeller**
Refining instructions regarding the submodule metaproject and database creating

### CODE REVIEW

**Comment by 3nids** [comment]
thanks this.

Although, `git submodule update --init --recursive` would be sufficient on the qwat level.

It's not necessary to create the extension as init_qwat.sh will do it.

**Comment by tudorbarascu** [comment]
@schoeller Do you have the time to rework your pull request based on the comments? Good morning and thanks for your work!

**Comment by schoeller** [comment]
@tudorbarascu : done

**Comment by 3nids** [comment]
Thanks a lot !

**Pull request merged**
