### PR TITLE
Network intervention simulation

### PR DESCRIPTION
**Pull request by benoitblanc**
This PR is related to https://github.com/qwat/qwat-data-model/pull/345

Actions are stored in python files and added to Pipe and Valve layers in QGS project :
* network leakage
* network interruption
* network pollution

### CODE REVIEW

**Comment by ponceta** [comment]
@benoitblanc could you edit this and prepare for merge by removing the WIP sign, since datamodel update is in master we should be able to merge this soon and provide feedbacks if necessary.

**Comment by benoitblanc** [comment]
@ponceta I have updated last QGIS project with actions to run network intervention simulation.

**Comment by ponceta** [comment]
@benoitblanc could you fix the git conflicts that must be resolved before merging?

**Comment by benoitblanc** [comment]
@ponceta I have resolved conflict on QGIS project, it was due to the difference of QGIS versions used in the 2 branches

**Comment by ponceta** [comment]
Thank you @benoitblanc

**Pull request merged**
