### PR TITLE
History viewer

### PR DESCRIPTION
**Pull request by mhugo**
A QGIS plugin to view audit logs.

Linked to https://github.com/qwat/QWAT/issues/117

This is inspired by https://github.com/3nids/postgres91plusauditor
The main differences with @3nids' plugin are:
- searchs are made by means of SQL queries on the DB
- the user (or the project generator) must map layer ids to database table names. Indeed, actions on a layer may be logged as events on tables with a different name. For instance, "vw_element_valve" is actually a view on "valve".

This version allows to
- search by layer, feature id, type of event, free text search in the data, dates
- be called from a python action with a layer id and a feature id
- replay (not revert) a logged event (thanks to https://github.com/qwat/qwat-data-model/pull/124)

Tests and UI feedback are still needed

cap

### CODE REVIEW

**Comment by 3nids** [comment]
looks promising! will have a look at this next week, thanks a lot!

**Comment by 3nids** [comment]
I didn't have a look yet but it would be worth creating its own repo maybe in qwat/postgreshistoryviewer
Since it is quite generic, it should not be tight to qwat data model. Hence, this would require a small interface to define connection settings and location of log table.

**Comment by ponceta** [comment]
Looks amazing yes, :+1:  for it's own repo.
I'll test it next week.

**Comment by mhugo** [comment]
See https://github.com/qwat/pg-history-viewer
This should not be specific anymore to qwat.
A new dialog allows to define the audit table and the db connection settings.
The table view has also been improved to incrementally load events (for big tables)

**Comment by mhugo** [comment]
For information, this has been published as an official QGIS plugin
http://plugins.qgis.org/plugins/pg_history_viewer/

**Comment by 3nids** [comment]
excellent, good job!!!

**Pull request closed without merging**
