### PR TITLE
Project improvements (remove duplicate Reseau group, add ouvrages_polygon, consistent lyr_names)

### PR DESCRIPTION
**Pull request by tudorbarascu**
At the moment there are two groups named ``Réseau``, one being the top one.
I think naming the top group to QWAT would be nice.
Moreover, duplicate groups/layers names are not directly supported by QGIS Server.

Furthermore, although the layer names are usually in plural form, there are some layers that are named at their singular form. Think it's better that we're consistent.

There's also the group ``Ouvrages`` with one of the two contained layers named ``ouvrage``.
Any suggestion here?

I realize that these are small changes but their absence is somehow not looking good.

What do you think?

### CODE REVIEW

**Comment by haubourg** [comment]
Thinking of it, I think the best name would be "Réseau (vue détaillée)". QWAT would imply that it  embedds all other groups like schematics annotations, zones...

**Comment by tudorbarascu** [comment]
Indeed, currently it looks like this:
screenshot from 2017-07-04 18-28-12

Thinking about it more, it would be nicer to just remove the second ``Réseau`` grouping and move the underlying layers to top group (conveniently named also ``Réseau``).
I already updated the PR, it would look like this:
screenshot from 2017-07-04 18-33-57

Thoughts?

**Comment by haubourg** [comment]
+1 for me. 
@qwat/qwat-psc ? Opinion on Tudor's proposal?

**Comment by tudorbarascu** [comment]
I also added the ``ouvrages_polygon`` layer like discussed in #202 .
As styling it's a water like gradient fill (with transparency) like so:
screen

**Comment by haubourg** [comment]
@qwat/qwat-psc I tested and like the more consistent naming Tudor proposes. Let's merge.

**Pull request merged**
